services:
  - type: web
    name: videoauthenticator
    env: python
    rootDir: videoauth
    buildCommand: "./build.sh"
    startCommand: "gunicorn videoauth.wsgi:application --bind 0.0.0.0:$PORT --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
